export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_PRODUCTS_DETAIL = 'GET_PRODUCTS_DETAIL'
export const POST_USER = 'POST_USER';
export const POST_PRODUCT = 'POST_PRODUCT';
export const PUT_PRODUCT = 'PUT_PRODUCT';
export const POST_BUSINESS = 'POST_BUSINESS';
export const GET_ALL_PRODUCTS_NAME = 'GET_ALL_PRODUCTS';
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const ORDER_BY_PRICE = 'ORDER_BY_PRICE';
export const POST_LOGIN = 'POST_LOGIN';
export const POST_LOGINBUSINESS = 'POST_LOGINBUSINESS';
export const GET_PRODUCTS_BUSINESS = 'GET_PRODUCTS_BUSINESS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const SET_PRODUCT_DETAIL = 'SET_PRODUCT_DETAIL';
export const GET_CITIES = 'GET_CITIES';
export const FILTER_BY_CITIES = 'FILTER_BY_CITIES';
export const GET_ALL_BUSINESS = 'GET_ALL_BUSINESS';
export const FILTER_BY_BUSINESS = 'FILTER_BY_BUSINESS';
export const CLEAN_USERS = 'CLEAN_USERS';
export const CLEAN_BUSINESS = 'CLEAN_BUSINESS';
export const GET_ALL_PROVINCES = 'GET_ALL_PROVINCES';
export const FILTER_BY_PROVINCES = 'FILTER_BY_PROVINCES';


