
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_PRODUCTS_DETAIL = 'GET_PRODUCTS_DETAIL'
export const POST_USER = 'POST_USER';
export const POST_PRODUCT = 'POST_PRODUCT';
export const PUT_PRODUCT = 'PUT_PRODUCT';
export const POST_BUSINESS = 'POST_BUSINESS';
export const GET_ALL_PRODUCTS_NAME = 'GET_ALL_PRODUCTS';
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const ORDER_BY_PRICE = 'ORDER_BY_PRICE';
export const POST_LOGIN = 'POST_LOGIN';
export const POST_LOGINBUSINESS = 'POST_LOGINBUSINESS';
export const GET_PRODUCTS_BUSINESS = 'GET_PRODUCTS_BUSINESS';
export const DESACTIVATE_PRODUCT = 'DESACTIVATE_PRODUCT';
export const SET_PRODUCT_DETAIL = 'SET_PRODUCT_DETAIL';
export const GET_ALL_CITIES = 'GET_ALL_CITIES';
export const FILTER_BY_CITIES = 'FILTER_BY_CITIES';
export const GET_ALL_BUSINESS = 'GET_ALL_BUSINESS';
export const FILTER_BY_BUSINESS = 'FILTER_BY_BUSINESS';
export const CLEAN_USERS = 'CLEAN_USERS';
export const CLEAN_USER_STATE = "CLEAN_USER_STATE";
export const CLEAN_BUSINESS = "CLEAN_BUSINESS";
export const CLEAN_BUSINESS_STATE = "CLEAN_BUSINESS_STATE";
export const FILTER_BY_PROVINCE_CITY = "FILTER_BY_PROVINCE_CITY";
export const GET_ALL_PROVINCES = "GET_ALL_PROVINCES";
export const FILTER_BY_PROVINCES = "FILTER_BY_PROVINCES";
export const PUT_USER = "PUT_USER";
export const CLEAN_PUT_USER = "CLEAN_PUT_USER";
export const GET_USER_BY_EMAIL = "GET_USER_BY_EMAIL";
export const PUT_BUSINESS = "PUT_BUSINESS";
export const ADD_TRAVEL = "ADD_TRAVEL";
export const GET_TRAVELS = "GET_TRAVELS";
export const GET_USERS = "GET_USERS";
export const GET_ACTIVE_USER = "GET_ACTIVE_USER";
export const GET_ALL_BRANCHES = "GET_ALL_BRANCHES";
export const FILTER_BY_BRANCHES = "FILTER_BY_BRANCHES";
export const FILTER_BY_BRANCHES_PROVINCES = "FILTER_BY_BRANCHES_PROVINCES";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const POST_PURCHASE = "POST_PURCHASE";
export const GET_BY_PURCHASE_EMAIL = "GET_BY_PURCHASE_EMAIL";
//Acciones del carrito (cart)
export const GET_CART = "GET_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const INCREMENT_ONE_IN_CART = "INCREMENT_ONE_IN_CART";
export const REMOVE_ONE_FROM_CART = "REMOVE_ONE_FROM_CART";
export const REMOVE_ALL_FROM_CART = "REMOVE_ALL_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";

//acciones sedes
export const POST_BRANCH = "POST_BRANCH";
export const DELETE_BRANCH = "DELETE_BRANCH";
export const EDIT_BRANCH = "EDIT_BRANCH";

//borrado lógico
export const DESACTIVATE_USER = "DESACTIVATE_USER";
export const DESACTIVATE_BUSINESS = "DESACTIVATE_BUSINESS";
export const ACTIVATE_USER = "ACTIVATE_USER";
export const ACTIVATE_BUSINESS = "ACTIVATE_BUSINESS";
export const DELETE_USER = "DELETE_USER";
export const DELETE_BUSINESS = "DELETE_BUSINESS";
export const ACTIVATE_PRODUCT = "ACTIVATE_PRODUCT";
export const ACTIVATE_BRANCH = "ACTIVATE_BRANCH";
// email
export const GET_EMAIL = "GET_EMAIL";
//REVIEW
export const POST_REVIEW = "POST_REVIEW";

// save images

// RESET STATE
export const RESET_INITIAL_STATE = 'RESET_INITIAL_STATE'


export const PASS_CHANGE = "PASS_CHANGE";


export const SAVE_IMAGE = "SAVE_IMAGE"; 

//Match get 
export const GET_MATCH = "GET_MATCH"
//Match put
export const PUT_MATCH = "PUT_MATCH"


//favoritos
export const GET_FAVOURITES = 'GET_FAVOURITES';
export const POST_FAVOURITES = 'POST_FAVOURITES';


